services:
  nest-app:
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
      - ${SSH_VOLUME}:/root/.ssh
      - ${GITCONFIG_VOLUME}:/root/.gitconfig
    ports:
      - "${HOST_PORT:-3000}:${CONTAINER_PORT:-3000}"
    environment:
      - NODE_ENV=development
      - PORT=${CONTAINER_PORT:-3000}
    tty: true
    stdin_open: true
    container_name: nest-app
    image: nest-app
    command: sh -c "npm run start:dev"
    networks:
      - shared-network

  mongo:
    image: mongo:latest
    container_name: mongo
    env_file: .env
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - shared-network

volumes:
  mongo-data:

networks:
  shared-network:
    driver: bridge
