services:
  nest-app:
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "${HOST_PORT:-3000}:${CONTAINER_PORT:-3000}"
    environment:
      - NODE_ENV=development
      - PORT=${CONTAINER_PORT:-3000}
    tty: true
    stdin_open: true
    container_name: nest-app
    # Inicia o servidor em modo debug
    command: npm run start:debug
